# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Schedule-Depend
version:      2.4
version_from: 
installdirs:  site
requires:
    Carp:                          0
    constant:                      0
    Cwd:                           2.12
    Data::Dumper:                  2.102
    File::Basename:                2.6
    FindBin:                       1.44
    FindBin::libs:                 1
    strict:                        0
    Symbol:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
